name: Publish

on:
  push:
    branches: [ "packaging"]
    tags:
      - '*'

permissions:
  packages: write
  contents: write
  #dummy text

jobs:
  package:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: [ "ubuntu-latest", "macos-latest" ]
#        OS: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@v1.4.3
    - name: Package app
      run: scala-cli .github/scripts/package.sc
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./artifacts/table-*"
