name: Publish

on:
  push:
    branches: [ "master" , "packaging"]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  package:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: [ "ubuntu-latest", "macos-latest" ]
#        OS: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@v1.4.3
#    - name: Run tests
#      run: scala-cli test .
    - name: Package app
      run: scala-cli .github/scripts/package.sc
